
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-lineal-saltos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod-lineal-saltos
  template:
    metadata:
      labels:
        app: pod-lineal-saltos
    spec:
      containers:
        - name: nodejs-app
          image: your-registry/pod-lineal-saltos:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "0.5"
              memory: "256Mi"