apiVersion: v1
kind: Service
metadata:
  name: pod-lineal-saltos-service
spec:
  selector:
    app: pod-lineal-saltos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer